import type { Metadata } from "next";
import { Geist, Geist_Mono, Playwrite_BE_VLG } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playwrite = Playwrite_BE_VLG({
  weight: ["100", "200", "300", "400"], 
  style: ["normal"], 
  display: "swap",  
  variable: "--font-playwrite", // tambahin biar bisa dipakai di className
});

export const metadata: Metadata = {
  title: "Adiwidia Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playwrite.variable} antialiased`}
      >
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
